name: kyeol_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon" # true 대신 이름을 직접 지정 (더 안정적임)
  ios: true
  image_path: "assets/icon/icon.png"
  # 아래 두 줄(adaptive)을 잠시 지우거나 주석 처리하고 테스트해 보세요!
  # adaptive_icon_background: "#F5F5DC" 
  # adaptive_icon_foreground: "assets/icon/icon.png"
